title: My Awesome Site
description: A site about awesome things
baseurl: "" # Leave this blank if using a custom domain
url: "https://statstree.io" # The full URL to your site
theme: jekyll-theme-minimal
author: Statstree
email: maragkakischaris@gmail.com

languages:
  default: "gr"
  en:
    label: "English"
    path: "/en"

permalink: pretty